# Generated by Django 5.0.1 on 2024-01-16 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('background_remover', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadedimage',
            name='upload_date',
            field=models.DateTimeField(),
        ),
    ]
